default:
  image: node:16

stages:
  - dev-build-affected
  - dev-build-all
  - dev-triggers-affected
  - dev-triggers-all
  - dev-deploy
  - prod-build-affected
  - prod-build-all
  - prod-triggers-affected
  - prod-triggers-all
  - prod-deploy

variables:
  DEV_K8S_DEPLOYMENT_FILE_1: 'k8s/dev/user-svc/dev/deployment.yaml'
  DEV_K8S_DEPLOYMENT_FILE_2: 'k8s/dev/tags-svc/dev/deployment.yaml'
  DEV_K8S_DEPLOYMENT_FILE_3: 'k8s/dev/media-svc/dev/deployment.yaml'
  PROD_K8S_DEPLOYMENT_FILE_1: 'k8s/live/user-svc/dev/deployment.yaml'
  PROD_K8S_DEPLOYMENT_FILE_2: 'k8s/live/tags-svc/dev/deployment.yaml'
  PROD_K8S_DEPLOYMENT_FILE_3: 'k8s/live/media-svc/dev/deployment.yaml'
  IMAGE_TAG: '$CI_COMMIT_SHORT_SHA'
  GITLAB_TOKEN: '$GITLAB_TOKEN'

dev-build-affected:
  stage: dev-build-affected
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "k8s"
  script:
    - npm ci --force
    - node ./dynamic-gitlab-ci.js "$(npx nx show projects --projects "apps/*" --exclude "*-e2e" --affected --base=HEAD~1 --json)" dev
    - cat dynamic-gitlab-ci.yml
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
      - dynamic-gitlab-ci.yml

dev-build-all:
  stage: dev-build-all
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "k8s"
  when: manual
  script:
    - npm ci --force
    - node ./dynamic-gitlab-ci.js "$(npx nx show projects --projects "apps/*" --exclude "*-e2e" --json)" dev
    - cat dynamic-gitlab-ci.yml
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
      - dynamic-gitlab-ci.yml

dev-triggers-affected:
  stage: dev-triggers-affected
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "k8s"
  needs:
    - dev-build-affected
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml # this file is generated on runtime in the build stage
        job: dev-build-affected
    strategy: depend

dev-triggers-all:
  stage: dev-triggers-all
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "k8s"
  needs:
    - dev-build-all
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml # this file is generated on runtime in the build stage
        job: dev-build-all
    strategy: depend

dev-deploy:
  stage: dev-deploy
  rules:
    - if: $CI_PIPELINE_SOURCE != "merge_request_event" && $CI_COMMIT_BRANCH != "k8s"
  when: manual
  #  needs:
  #    - job: dev-triggers-affected
  #      optional: true
  #    - job: dev-triggers-all
  #      optional: true
  script:
    # - apk update && apk add git
    - git config --global user.email "lucaslopatka@gmail.com"
    - git config --global user.name "Lucas Lopatka"
    - git clone "https://oauth2:$GITLAB_TOKEN@gitlab.com/technologycompany/mediashare.git" temp_repo
    - cd temp_repo
    # - git remote -v && (git checkout k8s || git checkout develop && git checkout -b k8s)
    - git checkout k8s
    - sed -i "s/user-svc:.*/user-svc:${CI_COMMIT_SHORT_SHA}/g" $DEV_K8S_DEPLOYMENT_FILE_1
    - sed -i "s/tags-svc:.*/tags-svc:${CI_COMMIT_SHORT_SHA}/g" $DEV_K8S_DEPLOYMENT_FILE_2
    - sed -i "s/media-svc:.*/media-svc:${CI_COMMIT_SHORT_SHA}/g" $DEV_K8S_DEPLOYMENT_FILE_3
    - git add . && git diff --cached
    - git commit -m "Update image tags ${CI_COMMIT_SHORT_SHA}" && git log -v
    - git push origin HEAD:k8s

prod-build-affected:
  stage: prod-build-affected
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  script:
    - npm ci --force
    - node ./dynamic-gitlab-ci.js "$(npx nx show projects --projects "apps/*" --exclude "*-e2e" --affected --base=HEAD~1 --json)"
    - cat dynamic-gitlab-ci.yml
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
      - dynamic-gitlab-ci.yml

prod-build-all:
  stage: prod-build-all
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  when: manual
  script:
    - npm ci --force
    - node ./dynamic-gitlab-ci.js "$(npx nx show projects --projects "apps/*" --exclude "*-e2e" --json)"
    - cat dynamic-gitlab-ci.yml
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
      - dynamic-gitlab-ci.yml

prod-triggers-affected:
  stage: prod-triggers-affected
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  needs:
    - prod-build-affected
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml # this file is generated on runtime in the build stage
        job: prod-build-affected
    strategy: depend

prod-triggers-all:
  stage: prod-triggers-all
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  needs:
    - prod-build-all
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml # this file is generated on runtime in the build stage
        job: prod-build-all
    strategy: depend

prod-deploy:
  stage: prod-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  when: manual
  needs:
    - job: prod-triggers-affected
      optional: true
    - job: prod-triggers-all
      optional: true
  script:
    # - apk update && apk add git
    - git config --global user.email "lucaslopatka@gmail.com"
    - git config --global user.name "Lucas Lopatka"
    - git clone "https://oauth2:$GITLAB_TOKEN@gitlab.com/technologycompany/mediashare.git" temp_repo
    - cd temp_repo
    # - git remote -v && (git checkout k8s || git checkout master && git checkout -b k8s)
    - git checkout k8s
    - sed -i "s/user-svc:.*/user-svc:${CI_COMMIT_SHORT_SHA}/g" $DEV_K8S_DEPLOYMENT_FILE_1
    - sed -i "s/tags-svc:.*/tags-svc:${CI_COMMIT_SHORT_SHA}/g" $DEV_K8S_DEPLOYMENT_FILE_2
    - sed -i "s/media-svc:.*/media-svc:${CI_COMMIT_SHORT_SHA}/g" $DEV_K8S_DEPLOYMENT_FILE_3
    - git add . && git diff --cached
    - git commit -m "Update image tags ${CI_COMMIT_SHORT_SHA}" && git log -v
    - git push origin HEAD:k8s
