apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: media-svc
  name: media-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: media-svc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/mediashare-network: 'true'
        io.kompose.service: media-svc
    spec:
      containers:
        - args:
            - npx
            - nx
            - serve
            - media-svc
            - --host=0.0.0.0
            - --configuration=development
            - --skip-nx-cache
          env:
            - name: APP_HOST
              value: 0.0.0.0
            - name: APP_NAME
              value: MediaSvc
            - name: APP_PREFIX
            - name: APP_TITLE
              value: MediaSvc
            - name: DB
              value: mediashare
            - name: DB_HOST
              value: cluster0.8x36b.mongodb.net # Update with your Atlas cluster hostname
            - name: DB_IS_ATLAS
              value: 'true'
            - name: DB_SSL
              value: 'true' # Ensure SSL is enabled for MongoDB Atlas
            - name: DB_SYNCHRONIZE
              value: 'true'
            - name: DB_TYPE
              value: mongodb
            - name: DB_URL
              value: mongodb+srv://msuser2:9oKsZ0fDEzXItjSt@cluster0.8x36b.mongodb.net/mediashare?retryWrites=true&w=majority
            - name: DB_USERNAME
              value: msuser2
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '3000'
            - name: SESSION_DB_COLLECTION
              value: session
            - name: SESSION_DB_NAME
              value: api-session
            - name: SESSION_SECRET
              value: this-is-my-secret-key
          image: registry.gitlab.com/technologycompany/mediashare/media-svc:8f9a3fe0
          name: media-svc
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
