apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: user-svc
  name: user-svc
spec:
  ports:
    - port: 80
      targetPort: 3001
  selector:
    io.kompose.service: user-svc
  type: ClusterIP # Set the service type to NodePort
